### ISSUE TITLE
Theme breaks on subdomains

### ISSUE THREAD

**Issue by mishari** [oeco/opendev-wptheme#10]
Please add the following line to your hosts file prior to testing:

```
128.199.88.241 opendevelopmentmekong.net cambodia.opendevelopmentmekong.net www.opendevelopmentmekong.net
```

When accessing http://opendevelopmentcambodia.net the theme appears fine. However when accessing http://cambodia.opendevelopmentmekong.net we're greeted mostly with a blank page:
![open_development_cambodia___sharing_information_about_cambodia_and_its_development_with_the_world_](https://cloud.githubusercontent.com/assets/503018/5990759/428d8580-a9f4-11e4-9613-fde941b3d75e.png)
But when one hovers one's mouse over the menu item (MEKONG), elements start to appear:
![open_development_cambodia___sharing_information_about_cambodia_and_its_development_with_the_world_](https://cloud.githubusercontent.com/assets/503018/5990764/7b0f01d6-a9f4-11e4-8f48-6432a8af4b21.png)

**Comment by Huyeng** [comment]
The problem caused by cutting the texts of ODM. As most of the posts were imported into the news through RSS Importer plugin which contain some html formats, so cutting of the string with affect to the html formats. For temporary, I just suspended those posts to clean up some html formats. 
If we can to deal with this issue with the script, it would be great.
