### ISSUE TITLE
Advanced search functionality

### ISSUE THREAD

**Issue by Numnov** [oeco/opendev-wptheme#34]
Implement this functionality as described in wireframe designs circulated by Internews on 12/13/14. This is not of utmost priority for launch but we require this to be implemented as one of the agreed deliverables of the OD child theme. Given the discussed intention for active development to cease after Friday 27 February 2015, we suggest that this is completed before that time.
![advance api github 3](https://cloud.githubusercontent.com/assets/4859982/6391147/9fb610d8-bde5-11e4-9ca1-4b900756ebcc.jpg)

**Comment by WillieShubert** [comment]
The advanced search functionality will work as displayed in the wireframe for the content types held and tagged within WordPress. Searches based on the WPCKAN plug-in (data archives) are determined by the functionality of the plug-in. It is important for us to keep these features distinct in order to use the tools (CKAN and WordPress) to the best of their capabilities.

**Comment by acorbi** [comment]
At this point, the wpckan plugin (v1.0.0beta3) should be implemented all the features identified on the conception phase. in case there is any functionality missing, please open an Issue on https://github.com/OpenDevelopmentMekong/wpckan
