### ISSUE TITLE
Viewing Map Layer

### ISSUE THREAD

**Issue by Huyeng** [oeco/opendev-wptheme#9]
Testing http://odmekong.geojournalism.org: 
Unable to view the layer after publishing.

**Comment by miguelpeixe** [comment]
For now the layer can only be visualized inside a map, since we don't have centering or any visualization setting in the layer. By the way, I was checking the layer you setup and the ELC layer is not a proper tilelayer URL. If you see the example below the form input you can see that {z} {x} {y} variables are necessary so the system can query the proper tiled images.

**Comment by DBishton** [comment]
Hi Miguel,

We urgently require clarification on this issue. Please provide more detail on what is required by JEO -- so far none of our team have been able to successfully display a layer on a map in JEO. 

For example, the following CartoDB layer does not show up: http://dbishton.cartodb.com/viz/7d320d44-aac8-11e4-9bb9-0e0c41326911/public_map

Additionally, we need to add a map with a three fairly heavy raster layers. CattoDB does not support this, and MapBox requires a paid subscription to host files of the size we have.

Do you have any suggested alternatives?

Many thanks.

**Comment by DBishton** [comment]
An update: The layer displays correctly with the correct format link: http://dbishton.cartodb.com/api/v2/viz/7d320d44-aac8-11e4-9bb9-0e0c41326911/viz.json

However, using CartoDB's html formatting for the legend produces an ill-formatted result:

![image](https://cloud.githubusercontent.com/assets/1206387/6059996/92aa9ed0-ad6a-11e4-937b-4fa6a30a9731.png)

If you could also advise on alternative hosting solutions for the raster layer in the above issue, that would be ideal.

**Comment by miguelpeixe** [comment]
Hi @DBishton,

The second url you posted is the correct one to use for CartoDB. JEO does not integrate the native CartoDB legends because it doesn't follow the map library standards for combining different layers legends. That's why we recommend you to manually paste the HTML for the legend on the layer editor inside JEO. That way, everytime you activate or deactivate layers, the proper legends will be displayed.

For the tilelayer url, I don't know how GeoServer can provide the url JEO requires. It should, since it's a standard url format for web maps.

If you'd like to look other map servers, I would recommend [TileStache](http://tilestache.org/). It's written in python and supports Mapnik maps and interactive MBTiles (MapBox rendered map files).

**Comment by Huyeng** [comment]
After fixing the Tilelayer on Geoserver, the title layer can generate and work with the JEO. 
This is Tilelayer of ELC map from Geoserver, that I added into JEO for testing. Well, it works fine now.  The CartoDB layer also working ok too. 
http://64.91.228.155:8181/geoserver/gwc/service/tms/1.0.0/Land_Natural_Resources%3Aelc_government_data_complete@EPSG%3A900913@png/{z}/{x}/{y}.png

See the screenshot: 
![screenshot_2](https://cloud.githubusercontent.com/assets/6613530/6840763/8a49c01e-d3b1-11e4-8c22-c970fa106250.jpg)

I conclude that the issue is closed.
